---
- hosts: all
  become: True
  tasks:
      - name: Ensure directory exists
        file:
            path: /tmp/testdir
            state: directory
            owner: root
            group: sys
            mode: 0755
            
      - name: Change ownership
        file:
            path: /tmp/testdir
            state: directory
            owner: frank
            group: frank