- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
      - name: ensure file exists
        copy:
            content: ""
            dest: /tmp/testfile
            force: no
            group: sys
            owner: root
            mode: 0555
