- name: create a file
  hosts: all
  become: True
  tasks:
      - name: ensure file exists
        copy:
            content: ""
            dest: /tmp/testfile
            force: no
            group: sys
            owner: root
            mode: 0555
