---
- hosts: all
  become: True
  tasks:
      - name: Ensure directory exists
        file:
            path: /tmp/testdir
            state: directory
            owner: root
            group: sys
            mode: 0755
            
      - name: Change ownership
        file:
            path: /tmp/testdir
            state: directory
            owner: frank
            group: 1000
            
      - name: Copy file to directory
        copy:
            src: /tower-demo/testfile.conf
            dst: /tmp/testdir/testfile.conf
            owner: frank
            group: 1000
            mode: '0644'