- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
- name: Restart OpenVPN services
  service:
    state: restarted
    name: "{{ item }}"
  with_items:
    - openvpn-bridge
    - openvpn-client
