- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Restart OpenVPN services
    systemd:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - 'openvpn-bridge'
      - 'openvpn-client'

