- name: restart the Transmission service
  hosts: all
  become: yes
  tasks:
  - name: Restart Transmission service
    systemd:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - 'transmission-daemon'

